import React, { useState, useEffect, useRef, useCallback } from 'react';
import {
  Box, Modal, ModalOverlay, ModalContent, ModalCloseButton,
  Heading, Text, Flex, Grid, Badge, Button, IconButton,
  VStack, HStack, Divider, Image, SimpleGrid,
  Circle, Icon, Spinner, Alert, AlertIcon, Input,
  Tooltip, Progress, AspectRatio, Skeleton, SkeletonText,
  useColorModeValue
} from '@chakra-ui/react';
import {
  FaTimes, FaBed, FaBath, FaRuler, FaMapMarkerAlt, FaCalendarAlt,
  FaChevronLeft, FaChevronRight, FaExternalLinkAlt, FaPhone, FaEnvelope,
  FaUpload, FaTrash, FaDownload, FaExpand, FaCompress, FaShare, FaHome,
  FaHeart, FaStar, FaBuilding, FaUser, FaTag, FaFilePdf, FaEye
} from 'react-icons/fa';
import { 
  fetchPropertyImages, 
  uploadPropertyImageV2,
  deletePropertyImage,
  uploadPropertyBrochure
} from '../../../services/propertyService';
import { submitContactUs } from '../../../services/homeservices/homeService';
import { showSuccessToast, showErrorToast } from '../../../utils/toastUtils';
import DeleteConfirmationModal from '../../../components/common/DeleteConfirmationModal';

const floatingButtonStyle = {
  bg: 'rgba(30,30,30,0.75)',
  color: 'white',
  boxShadow: '0 4px 16px rgba(0,0,0,0.25)',
  borderRadius: 'full',
  backdropFilter: 'blur(8px)',
  _hover: {
    bg: 'rgba(30,30,30,0.9)',
    color: 'white',
    transform: 'scale(1.1)',
    boxShadow: '0 8px 24px rgba(0,0,0,0.35)',
  },
  transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
};

const PropertyPreview = ({ isOpen, onClose, property, isViewOnly = false }) => {
  const [propertyImages, setPropertyImages] = useState([]);
  const [currentImageIndex, setCurrentImageIndex] = useState(0);
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState(null);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [imageToDelete, setImageToDelete] = useState(null);
  const [isDeleteModalOpen, setIsDeleteModalOpen] = useState(false);
  const [contactLoading, setContactLoading] = useState(false);
  const [brochureUploading, setBrochureUploading] = useState(false);
  const [brochureUrl, setBrochureUrl] = useState(null);
  const fileInputRef = useRef();
  const brochureInputRef = useRef();

  // Color mode values
  const bgColor = useColorModeValue('white', 'gray.800');
  const cardBg = useColorModeValue('gray.50', 'gray.700');
  const borderColor = useColorModeValue('gray.200', 'gray.600');
  const textColor = useColorModeValue('gray.800', 'white');
  const subTextColor = useColorModeValue('gray.600', 'gray.300');

  const fetchPropertyImagesData = useCallback(async () => {
    if (!property?._id) return;
    setLoading(true);
    setError(null);
    try {
      const response = await fetchPropertyImages(property._id);
      setPropertyImages(response.data || []);
    } catch (err) {
      console.error('Failed to fetch property images:', err);
      setError('Failed to load property images');
      showErrorToast('Failed to load property images');
    } finally {
      setLoading(false);
    }
  }, [property?._id]);

  useEffect(() => {
    if (isOpen && property?._id) {
      fetchPropertyImagesData();
      // Set brochure URL from property - use URL as-is (generated by cloudinary.url() like documents)
      const url = property?.brochureUrl || null;
      if (url) {
        // Remove query parameters if any, but keep the URL structure intact
        const cleanUrl = url.split('?')[0];
        setBrochureUrl(cleanUrl);
      } else {
        setBrochureUrl(null);
      }
    }
  }, [isOpen, property?._id, property?.brochureUrl, fetchPropertyImagesData]);

  const handleImageUpload = async (event) => {
    const file = event.target.files[0];
    if (!file) return;

    // Validate file type
    if (!file.type.startsWith('image/')) {
      showErrorToast('Please select an image file');
      return;
    }

    // Validate file size (5MB limit)
    if (file.size > 5 * 1024 * 1024) {
      showErrorToast('Please select an image smaller than 5MB');
      return;
    }

    setUploading(true);
    setUploadProgress(0);

    try {
      // Simulate upload progress
      const progressInterval = setInterval(() => {
        setUploadProgress(prev => {
          if (prev >= 90) {
            clearInterval(progressInterval);
            return 90;
          }
          return prev + 10;
        });
      }, 100);

      const response = await uploadPropertyImageV2(property._id, file);
      
      clearInterval(progressInterval);
      setUploadProgress(100);

      // Add new image to the list
      setPropertyImages(prev => [...prev, response.data]);
      setCurrentImageIndex(propertyImages.length); // Show the new image
      
      showSuccessToast('Image uploaded successfully');
      
      // Clear the file input
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    } catch (error) {
      console.error('Failed to upload image:', error);
      showErrorToast('Failed to upload image');
    } finally {
      setUploading(false);
      setUploadProgress(0);
    }
  };

  const handleDeleteImage = (image) => {
    setImageToDelete(image);
    setIsDeleteModalOpen(true);
  };

  const confirmDeleteImage = async () => {
    if (!imageToDelete) return;

    try {
      await deletePropertyImage(property._id, imageToDelete._id);
      
      // Remove image from the list
      setPropertyImages(prev => prev.filter(img => img._id !== imageToDelete._id));
      
      // Adjust current index if needed
      if (currentImageIndex >= propertyImages.length - 1) {
        setCurrentImageIndex(Math.max(0, propertyImages.length - 2));
      }
      
      showSuccessToast('Image deleted successfully');
    } catch (error) {
      console.error('Failed to delete image:', error);
      showErrorToast('Failed to delete image');
    } finally {
      setIsDeleteModalOpen(false);
      setImageToDelete(null);
    }
  };

  const formatPrice = (price) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0
    }).format(price);
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  };

  const nextImage = () => {
    setCurrentImageIndex((prev) => (prev + 1) % propertyImages.length);
  };

  const prevImage = () => {
    setCurrentImageIndex((prev) => (prev - 1 + propertyImages.length) % propertyImages.length);
  };

  const getStatusColor = (status) => {
    switch (status?.toUpperCase()) {
      case 'FOR SALE': return 'green';
      case 'FOR RENT': return 'blue';
      case 'SOLD': return 'red';
      case 'RENTED': return 'purple';
      default: return 'gray';
    }
  };

  const shareProperty = () => {
    const url = window.location.href;
    if (navigator.share) {
      navigator.share({
        title: property.name,
        text: `Check out this property: ${property.name} - ${formatPrice(property.price)}`,
        url: url
      });
    } else {
      navigator.clipboard.writeText(url);
      showSuccessToast('Property link copied to clipboard');
    }
  };

  const toggleFullscreen = () => {
    setIsFullscreen(!isFullscreen);
  };

  const handleBrochureUpload = async (event) => {
    const file = event.target.files[0];
    if (!file) return;

    // Validate file type
    if (file.type !== 'application/pdf') {
      showErrorToast('Please select a PDF file');
      return;
    }

    // Validate file size (10MB limit)
    if (file.size > 10 * 1024 * 1024) {
      showErrorToast('Please select a PDF smaller than 10MB');
      return;
    }

    setBrochureUploading(true);

    try {
      const response = await uploadPropertyBrochure(property._id, file);
      // Use brochureUrl (generated by cloudinary.url() like documents)
      const url = response.data?.brochureUrl || response.data?.data?.brochureUrl || response.data?.secureUrl || response.data?.data?.secureUrl;
      if (url) {
        // Remove query parameters if any
        const cleanUrl = url.split('?')[0];
        setBrochureUrl(cleanUrl);
        showSuccessToast('Brochure uploaded successfully');
      } else {
        console.error('Brochure URL not found in response:', response);
        showErrorToast('Brochure uploaded but URL not received');
      }
      
      // Clear the file input
      if (brochureInputRef.current) {
        brochureInputRef.current.value = '';
      }
    } catch (error) {
      console.error('Failed to upload brochure:', error);
      const errorMessage = error?.response?.data?.message || 'Failed to upload brochure';
      showErrorToast(errorMessage);
    } finally {
      setBrochureUploading(false);
    }
  };

  const handleViewBrochure = () => {
    if (brochureUrl) {
      // Open PDF in new tab - same as document management
        window.open(brochureUrl, '_blank');
    } else {
      showErrorToast('Brochure URL not available');
    }
  };

  const handleDownloadBrochure = async () => {
    // Download locally - same approach as document management in booking viewers
    if (!brochureUrl) {
      showErrorToast('Brochure URL not available');
      return;
    }

    try {
      // Fetch as blob to force download (works with cross-origin URLs like Cloudinary)
      const response = await fetch(brochureUrl);
      if (!response.ok) {
        throw new Error('Failed to fetch brochure');
      }
      
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
      link.href = url;
      link.download = `${property?.name || 'Property'}_Brochure.pdf`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
        showSuccessToast('Brochure download started');
      } catch (error) {
      console.error('Failed to download brochure:', error);
      showErrorToast('Failed to download brochure. Please try again.');
    }
  };

  const handleContactAgent = async () => {
    try {
      // Get user data from localStorage
      const authData = localStorage.getItem('auth');
      if (!authData) {
        showErrorToast('Please login to contact agent');
        return;
      }

      const parsedAuth = JSON.parse(authData);
      const userData = parsedAuth.data;

      if (!userData.firstName || !userData.lastName || !userData.email || !userData.phoneNumber) {
        showErrorToast('User information incomplete. Please update your profile.');
        return;
      }

      setContactLoading(true);

      // Prepare contact message
      const message = `Hi,\n\nI'm interested in the property: ${property.name}\n\nProperty Details:\n- Price: ${formatPrice(property.price)}\n- Address: ${property.propertyAddress?.street}, ${property.propertyAddress?.area}, ${property.propertyAddress?.city}\n\nPlease provide more information about this property.\n\nThank you!`;

      // Submit contact request
      await submitContactUs({
        name: `${userData.firstName} ${userData.lastName}`,
        email: userData.email,
        phone: userData.phoneNumber,
        description: message
      });

      showSuccessToast('Contact request sent successfully!');
    } catch (error) {
      console.error('Error sending contact request:', error);
      showErrorToast('Failed to send contact request. Please try again.');
    } finally {
      setContactLoading(false);
    }
  };

  // Reset fullscreen when modal closes
  useEffect(() => {
    if (!isOpen) {
      setIsFullscreen(false);
    }
  }, [isOpen]);

  if (!isOpen || !property) return null;

  const currentImage = propertyImages[currentImageIndex] || null;
  const hasImages = propertyImages.length > 0;

  return (
    <Modal 
      isOpen={isOpen} 
      onClose={onClose} 
      size={isFullscreen ? "full" : { base: "full", sm: "full", md: "7xl" }} 
      isCentered={!isFullscreen}
    >
      <ModalOverlay bg="blackAlpha.700" backdropFilter="blur(12px)" />
      <ModalContent
        maxW={isFullscreen ? "100vw" : { base: "100vw", sm: "100vw", md: "98vw", lg: "95vw", xl: "90vw" }}
        maxH={isFullscreen ? "100vh" : { base: "100vh", sm: "100vh", md: "98vh", lg: "95vh" }}
        borderRadius={isFullscreen ? "0" : { base: "0", sm: "0", md: "3xl" }}
        overflow="hidden"
        bg={bgColor}
        boxShadow={isFullscreen ? "none" : "0 25px 50px rgba(0, 0, 0, 0.25)"}
        mx={isFullscreen ? 0 : { base: 0, sm: 0, md: 4 }}
        my={isFullscreen ? 0 : { base: 0, sm: 0, md: 4 }}
        p={0}
        border={isFullscreen ? "none" : "1px solid"}
        borderColor={borderColor}
      >
        <ModalCloseButton
          position="absolute"
          top={{ base: 3, sm: 4, md: 6 }}
          right={{ base: 3, sm: 4, md: 6 }}
          zIndex={10}
          size={{ base: "sm", sm: "md", md: "lg" }}
          {...floatingButtonStyle}
        />

        <Box maxH={{ base: "100vh", sm: "100vh", md: "95vh", lg: "90vh" }} overflowY="auto" p={0}>
          {/* Enhanced Image Gallery Section - AdminMeetings Style */}
          <Box position="relative" h={{ base: '400px', sm: '450px', md: '500px', lg: '600px' }} m={0} p={0}>
            {loading ? (
              <Flex justify="center" align="center" h="full" bg={cardBg}>
                <VStack spacing={6}>
                  <Spinner size="xl" color="brand.500" thickness="4px" />
                  <Text color={subTextColor} fontSize="lg" fontWeight="medium">Loading images...</Text>
                </VStack>
              </Flex>
            ) : error ? (
              <Flex justify="center" align="center" h="full" bg={cardBg}>
                <Alert status="error" borderRadius="xl" maxW="400px" bg="red.50" border="1px solid" borderColor="red.200">
                  <AlertIcon />
                  {error}
                </Alert>
              </Flex>
            ) : hasImages ? (
              <>
                {/* Enhanced Main Image with Better Styling */}
                <Box position="relative" h="full" overflow="hidden">
                  <Image
                    src={currentImage?.displayUrl || currentImage?.originalUrl}
                    alt={`${property.name} - Image ${currentImageIndex + 1}`}
                    w="full"
                    h="full"
                    objectFit="cover"
                    fallbackSrc="https://via.placeholder.com/800x500?text=Property+Image"
                    transition="all 0.5s cubic-bezier(0.4, 0, 0.2, 1)"
                    _hover={{ transform: 'scale(1.05)' }}
                    filter="brightness(0.9) contrast(1.1)"
                  />
                  
                  {/* Gradient Overlay for Better Text Visibility */}
                  <Box
                    position="absolute"
                    top="0"
                    left="0"
                    right="0"
                    bottom="0"
                    bg="linear-gradient(180deg, rgba(0,0,0,0.3) 0%, transparent 30%, transparent 70%, rgba(0,0,0,0.4) 100%)"
                    pointerEvents="none"
                  />
                </Box>
                
                {/* Enhanced Image Navigation - AdminMeetings Style */}
                {propertyImages.length > 1 && (
                  <>
                    <IconButton
                      icon={<FaChevronLeft />}
                      position="absolute"
                      left={4}
                      top="50%"
                      transform="translateY(-50%)"
                      onClick={prevImage}
                      aria-label="Previous image"
                      size="lg"
                      bg="rgba(0,0,0,0.7)"
                      color="white"
                      _hover={{
                        bg: "rgba(0,0,0,0.9)",
                        transform: "translateY(-50%) scale(1.1)",
                        boxShadow: "0 8px 24px rgba(0,0,0,0.4)"
                      }}
                      transition="all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"
                      borderRadius="full"
                      backdropFilter="blur(8px)"
                      border="1px solid"
                      borderColor="whiteAlpha.200"
                    />
                    <IconButton
                      icon={<FaChevronRight />}
                      position="absolute"
                      right={4}
                      top="50%"
                      transform="translateY(-50%)"
                      onClick={nextImage}
                      aria-label="Next image"
                      size="lg"
                      bg="rgba(0,0,0,0.7)"
                      color="white"
                      _hover={{
                        bg: "rgba(0,0,0,0.9)",
                        transform: "translateY(-50%) scale(1.1)",
                        boxShadow: "0 8px 24px rgba(0,0,0,0.4)"
                      }}
                      transition="all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"
                      borderRadius="full"
                      backdropFilter="blur(8px)"
                      border="1px solid"
                      borderColor="whiteAlpha.200"
                    />
                  </>
                )}

                {/* Enhanced Image Counter - AdminMeetings Style */}
                <Box
                  position="absolute"
                  bottom={4}
                  right={4}
                  bg="rgba(0,0,0,0.8)"
                  color="white"
                  px={3}
                  py={1}
                  borderRadius="full"
                  fontSize="sm"
                  fontWeight="bold"
                  backdropFilter="blur(12px)"
                  border="1px solid"
                  borderColor="whiteAlpha.200"
                  boxShadow="0 4px 12px rgba(0,0,0,0.3)"
                >
                  {currentImageIndex + 1} / {propertyImages.length}
                </Box>

                {/* Enhanced Image Actions - AdminMeetings Style */}
                <HStack
                  position="absolute"
                  top={4}
                  right={4}
                  spacing={2}
                  zIndex={15}
                >
                  {!isViewOnly && (
                    <Tooltip label="Upload Image" placement="bottom">
                      <IconButton
                        icon={<FaUpload />}
                        size="md"
                        onClick={() => fileInputRef.current?.click()}
                        aria-label="Upload image"
                        bg="rgba(0,0,0,0.7)"
                        color="white"
                        _hover={{
                          bg: "rgba(0,0,0,0.9)",
                          transform: "scale(1.1)",
                          boxShadow: "0 8px 24px rgba(0,0,0,0.4)"
                        }}
                        transition="all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"
                        borderRadius="full"
                        backdropFilter="blur(8px)"
                        border="1px solid"
                        borderColor="whiteAlpha.200"
                      />
                    </Tooltip>
                  )}
                  <Tooltip label="Fullscreen" placement="bottom">
                    <IconButton
                      icon={isFullscreen ? <FaCompress /> : <FaExpand />}
                      size="md"
                      onClick={toggleFullscreen}
                      aria-label="Toggle fullscreen"
                      bg="rgba(0,0,0,0.7)"
                      color="white"
                      _hover={{
                        bg: "rgba(0,0,0,0.9)",
                        transform: "scale(1.1)",
                        boxShadow: "0 8px 24px rgba(0,0,0,0.4)"
                      }}
                      transition="all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"
                      borderRadius="full"
                      backdropFilter="blur(8px)"
                      border="1px solid"
                      borderColor="whiteAlpha.200"
                    />
                  </Tooltip>
                  <Tooltip label="Share Property" placement="bottom">
                    <IconButton
                      icon={<FaShare />}
                      size="md"
                      onClick={shareProperty}
                      aria-label="Share property"
                      bg="rgba(0,0,0,0.7)"
                      color="white"
                      _hover={{
                        bg: "rgba(0,0,0,0.9)",
                        transform: "scale(1.1)",
                        boxShadow: "0 8px 24px rgba(0,0,0,0.4)"
                      }}
                      transition="all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"
                      borderRadius="full"
                      backdropFilter="blur(8px)"
                      border="1px solid"
                    />
                  </Tooltip>
                </HStack>

                {/* Enhanced Upload Progress */}
                {uploading && (
                  <Box
                    position="absolute"
                    bottom={0}
                    left={0}
                    right={0}
                    bg="whiteAlpha.950"
                    p={4}
                    backdropFilter="blur(8px)"
                  >
                    <Progress 
                      value={uploadProgress} 
                      colorScheme="brand" 
                      size="md" 
                      borderRadius="full"
                      bg="gray.200"
                    />
                    <Text fontSize="sm" textAlign="center" mt={2} fontWeight="medium">
                      Uploading... {uploadProgress}%
                    </Text>
                  </Box>
                )}
              </>
            ) : (
              <Flex justify="center" align="center" h="full" bg={cardBg}>
                <VStack spacing={6}>
                  <Circle size="80px" bg="gray.200" color="gray.400">
                    <FaMapMarkerAlt size={32} />
                  </Circle>
                  <Text color={subTextColor} fontSize="lg" fontWeight="medium">No images available</Text>
                  {!isViewOnly && (
                    <Button
                      leftIcon={<FaUpload />}
                      colorScheme="brand"
                      variant="outline"
                      size="md"
                      onClick={() => fileInputRef.current?.click()}
                      borderRadius="xl"
                      _hover={{
                        transform: "translateY(-2px)",
                        boxShadow: "0 8px 24px rgba(102, 126, 234, 0.3)"
                      }}
                      transition="all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"
                    >
                      Upload First Image
                    </Button>
                  )}
                </VStack>
              </Flex>
            )}

            {/* Enhanced Status Badge - AdminMeetings Style */}
            <Badge
              position="absolute"
              top={4}
              left={4}
              colorScheme={getStatusColor(property.propertyStatus)}
              variant="solid"
              px={3}
              py={1}
              borderRadius="full"
              fontSize="sm"
              fontWeight="bold"
              textTransform="uppercase"
              boxShadow="lg"
              backdropFilter="blur(12px)"
              border="1px solid"
              borderColor="whiteAlpha.200"
              letterSpacing="wide"
            >
              {property.propertyStatus}
            </Badge>

            {/* Hidden file inputs */}
            <Input
              ref={fileInputRef}
              type="file"
              accept="image/*"
              onChange={handleImageUpload}
              display="none"
            />
            <Input
              ref={brochureInputRef}
              type="file"
              accept="application/pdf"
              onChange={handleBrochureUpload}
              display="none"
            />
          </Box>

          {/* Content Section - Minimalistic */}
          <Box p={{ base: 4, sm: 5, md: 6 }} pb={{ base: 4, sm: 5, md: 6 }}>
            <VStack spacing={4} align="stretch">
              {/* Header - Minimalistic */}
              <Box>
                <VStack spacing={2} align="start">
                  {/* Property Type and Status Badges */}
                  <HStack spacing={2} flexWrap="wrap">
                    {property.propertyTypeId?.typeName && (
                      <Badge
                        colorScheme="purple"
                        variant="subtle"
                        px={2}
                        py={1}
                        borderRadius="md"
                        fontSize="xs"
                        fontWeight="medium"
                      >
                        {property.propertyTypeId.typeName}
                      </Badge>
                    )}
                    <Badge
                      colorScheme={getStatusColor(property.propertyStatus)}
                      variant="subtle"
                      px={2}
                      py={1}
                      borderRadius="md"
                      fontSize="xs"
                      fontWeight="medium"
                    >
                      {property.propertyStatus}
                    </Badge>
                  </HStack>

                  <Heading 
                    size={{ base: "md", sm: "lg" }} 
                    color={textColor} 
                    fontWeight="bold"
                    lineHeight="tight"
                  >
                    {property.name}
                  </Heading>
                  
                  <Flex align="center" color={subTextColor} fontSize="xs" gap={1} flexWrap="wrap">
                    <Icon as={FaMapMarkerAlt} color="brand.500" size="xs" />
                    <Text noOfLines={2} fontSize="xs">
                      {`${property.propertyAddress?.street || ''}, ${property.propertyAddress?.area || ''}, ${property.propertyAddress?.city || ''}, ${property.propertyAddress?.state || ''} ${property.propertyAddress?.zipOrPinCode || ''}`.replace(/^,\s*|,\s*$/g, '').replace(/,\s*,/g, ',')}
                    </Text>
                  </Flex>
                  
                  <Text 
                    fontSize={{ base: "lg", sm: "xl" }} 
                    fontWeight="bold" 
                    color="brand.500"
                    lineHeight="tight"
                  >
                    {formatPrice(property.price)}
                  </Text>
                </VStack>
              </Box>

              {/* Owner Information Section - Minimalistic */}
              {property.owner && (
                <Box
                  bg={cardBg}
                  borderRadius="lg"
                  p={4}
                border="1px solid"
                borderColor={borderColor}
                >
                  <Flex align="center" mb={3} gap={2}>
                    <Icon as={FaUser} color="brand.500" size="sm" />
                    <Text fontSize="sm" fontWeight="semibold" color={textColor}>Agent</Text>
                  </Flex>
                  
                  <VStack spacing={2} align="stretch">
                    <HStack spacing={2}>
                      <Text fontSize="xs" color={subTextColor} minW="60px">Name:</Text>
                      <Text fontSize="sm" fontWeight="medium" color={textColor}>
                        {property.owner.firstName} {property.owner.lastName}
                      </Text>
                    </HStack>
                    
                    {property.owner.email && (
                      <HStack spacing={2}>
                        <Text fontSize="xs" color={subTextColor} minW="60px">Email:</Text>
                        <HStack spacing={1} flex={1}>
                          <Icon as={FaEnvelope} color="brand.500" size="xs" />
                          <Text fontSize="xs" fontWeight="medium" color={textColor} noOfLines={1}>
                            {property.owner.email}
                          </Text>
                        </HStack>
                      </HStack>
                    )}
                    
                    {property.owner.phoneNumber && (
                      <HStack spacing={2}>
                        <Text fontSize="xs" color={subTextColor} minW="60px">Phone:</Text>
                        <HStack spacing={1}>
                          <Icon as={FaPhone} color="brand.500" size="xs" />
                          <Text fontSize="xs" fontWeight="medium" color={textColor}>
                            {property.owner.phoneNumber}
                          </Text>
                        </HStack>
                      </HStack>
                    )}
                  </VStack>
                </Box>
              )}

              {/* Features Grid - Minimalistic */}
              <Box 
                bg={cardBg}
                borderRadius="lg"
                p={4}
                border="1px solid"
                borderColor={borderColor}
              >
                <Text 
                  fontSize="sm"
                  fontWeight="semibold" 
                  color={textColor} 
                  mb={3}
                >
                  Features
                </Text>
                
                <SimpleGrid columns={{ base: 2, sm: 3, md: 4 }} spacing={3}>
                  {/* BHK - Minimalistic */}
                  {property.features?.bhk && (
                    <Box
                      bg="white"
                      borderRadius="md"
                      p={3}
                      textAlign="center"
                      border="1px solid"
                      borderColor={borderColor}
                    >
                      <Icon as={FaHome} color="purple.500" size="sm" mb={1} />
                      <Text fontSize="lg" fontWeight="bold" color={textColor}>
                        {property.features.bhk} BHK
                      </Text>
                      <Text fontSize="xs" color={subTextColor}>
                        Bedroom Hall Kitchen
                      </Text>
                    </Box>
                  )}

                  {/* Bedrooms - Minimalistic */}
                  <Box
                    bg="white"
                    borderRadius="md"
                    p={3}
                    textAlign="center"
                    border="1px solid"
                    borderColor={borderColor}
                  >
                    <Icon as={FaBed} color="brand.500" size="sm" mb={1} />
                    <Text fontSize="lg" fontWeight="bold" color={textColor}>
                      {property.features?.bedRooms || 0}
                    </Text>
                    <Text fontSize="xs" color={subTextColor}>
                      Bedrooms
                    </Text>
                  </Box>

                  {/* Bathrooms - Minimalistic */}
                  <Box
                    bg="white"
                    borderRadius="md"
                    p={3}
                    textAlign="center"
                    border="1px solid"
                    borderColor={borderColor}
                  >
                    <Icon as={FaBath} color="blue.500" size="sm" mb={1} />
                    <Text fontSize="lg" fontWeight="bold" color={textColor}>
                      {property.features?.bathRooms || 0}
                    </Text>
                    <Text fontSize="xs" color={subTextColor}>
                      Bathrooms
                    </Text>
                  </Box>

                  {/* Square Feet - Minimalistic */}
                  <Box
                    bg="white"
                    borderRadius="md"
                    p={3}
                    textAlign="center"
                    border="1px solid"
                    borderColor={borderColor}
                  >
                    <Icon as={FaRuler} color="green.500" size="sm" mb={1} />
                    <Text fontSize="lg" fontWeight="bold" color={textColor}>
                      {property.features?.areaInSquarFoot || 0}
                    </Text>
                    <Text fontSize="xs" color={subTextColor}>
                      sq.ft
                    </Text>
                  </Box>

                  {/* Listed Date - Minimalistic */}
                  <Box
                    bg="white"
                    borderRadius="md"
                    p={3}
                    textAlign="center"
                    border="1px solid"
                    borderColor={borderColor}
                  >
                    <Icon as={FaCalendarAlt} color="purple.500" size="sm" mb={1} />
                    <Text fontSize="sm" fontWeight="bold" color={textColor} noOfLines={1}>
                      {property.listedDate ? formatDate(property.listedDate) : 'N/A'}
                    </Text>
                    <Text fontSize="xs" color={subTextColor}>
                      Listed
                    </Text>
                  </Box>
                </SimpleGrid>
              </Box>

              <Divider borderColor={borderColor} />

              {/* Description - Minimalistic */}
              {property.description && (
                <Box
                  bg={cardBg}
                  borderRadius="lg"
                  p={4}
                  border="1px solid"
                  borderColor={borderColor}
                >
                  <Flex align="center" gap={2} mb={2}>
                    <Icon as={FaBuilding} color="brand.500" size="sm" />
                    <Text fontSize="sm" fontWeight="semibold" color={textColor}>Description</Text>
                  </Flex>
                  <Text 
                    color={subTextColor} 
                    lineHeight="1.6" 
                    fontSize="sm"
                    whiteSpace="pre-wrap"
                  >
                    {property.description}
                  </Text>
              </Box>
              )}

              {/* Amenities - Minimalistic */}
              {property.features?.amenities?.length > 0 && (
                <Box
                  bg={cardBg}
                  borderRadius="lg"
                  p={4}
                  border="1px solid"
                  borderColor={borderColor}
                >
                  <Flex align="center" gap={2} mb={3}>
                    <Icon as={FaHome} color="green.500" size="sm" />
                    <Text fontSize="sm" fontWeight="semibold" color={textColor}>Amenities</Text>
                  </Flex>
                  <SimpleGrid columns={{ base: 2, sm: 3, md: 4 }} spacing={2}>
                    {property.features.amenities.map((amenity) => (
                      <Flex 
                        key={amenity} 
                        align="center" 
                        gap={2}
                        p={2}
                        bg="white"
                        borderRadius="md"
                        border="1px solid"
                        borderColor={borderColor}
                      >
                        <Circle size="6px" bg="green.500" />
                        <Text fontSize="xs" color={textColor}>
                          {amenity}
                        </Text>
                      </Flex>
                    ))}
                  </SimpleGrid>
                </Box>
              )}

              {/* Brochure Section - Minimalistic */}
              <Box
                bg={cardBg}
                borderRadius="lg"
                p={4}
                border="1px solid"
                borderColor={borderColor}
              >
                <Flex align="center" mb={3} justify="space-between">
                  <Flex align="center" gap={2}>
                    <Icon as={FaFilePdf} color="red.500" size="sm" />
                    <Text fontSize="sm" fontWeight="semibold" color={textColor}>Brochure</Text>
                  </Flex>
                  {!isViewOnly && (
                    <Button
                      leftIcon={<FaUpload />}
                      size="xs"
                      variant="outline"
                      colorScheme="brand"
                      onClick={() => brochureInputRef.current?.click()}
                      isLoading={brochureUploading}
                      loadingText="Uploading..."
                    >
                      {brochureUrl ? 'Update' : 'Upload'}
                    </Button>
                  )}
                </Flex>
                
                {brochureUrl ? (
                  <HStack spacing={2} justify="center">
                      <Button
                        leftIcon={<FaEye />}
                        colorScheme="blue"
                      variant="outline"
                      size="sm"
                        onClick={handleViewBrochure}
                      >
                      View
                      </Button>
                      <Button
                        leftIcon={<FaDownload />}
                        colorScheme="green"
                      variant="outline"
                      size="sm"
                        onClick={handleDownloadBrochure}
                      >
                      Download
                      </Button>
                    </HStack>
                ) : (
                  <Text fontSize="xs" color={subTextColor} textAlign="center" py={2}>
                    No brochure available
                      </Text>
                )}
              </Box>

              {/* Location & Actions - Minimalistic */}
              <Box
                bg={cardBg}
                borderRadius="lg"
                p={4}
                border="1px solid"
                borderColor={borderColor}
              >
                <VStack spacing={3} align="stretch">
                  <Flex align="center" gap={2} mb={2}>
                    <Icon as={FaMapMarkerAlt} color="orange.500" size="sm" />
                    <Text fontSize="sm" fontWeight="semibold" color={textColor}>Location</Text>
                  </Flex>
                      <Button
                        leftIcon={<FaExternalLinkAlt />}
                        variant="outline"
                        colorScheme="brand"
                    size="sm"
                        onClick={() => {
                          const url = `https://www.google.com/maps/search/?api=1&query=${property.propertyAddress?.location?.lat},${property.propertyAddress?.location?.lng}`;
                          window.open(url, '_blank');
                        }}
                  >
                    View on Maps
                      </Button>
                  <Button
                    leftIcon={<FaPhone />}
                    colorScheme="brand"
                    variant="solid"
                    size="sm"
                    isLoading={contactLoading}
                    loadingText="Sending..."
                    onClick={handleContactAgent}
                  >
                    Contact Agent
                  </Button>
                </VStack>
              </Box>

              {/* Enhanced Image Thumbnails - AdminMeetings Style */}
              {hasImages && (
                <Box>
                  <Flex justify="space-between" align="center" mb={{ base: 4, sm: 6 }}>
                    <Heading size={{ base: "md", sm: "lg" }} color={textColor}>Gallery</Heading>
                    {!isViewOnly && (
                      <Button
                        leftIcon={<FaUpload />}
                        size={{ base: "sm", sm: "md" }}
                        variant="outline"
                        colorScheme="brand"
                        onClick={() => fileInputRef.current?.click()}
                        borderRadius="xl"
                        _hover={{
                          transform: "translateY(-2px)",
                          boxShadow: "0 8px 24px rgba(102, 126, 234, 0.3)"
                        }}
                        transition="all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"
                      >
                        Add Image
                      </Button>
                    )}
                  </Flex>
                  <SimpleGrid columns={{ base: 3, sm: 4, md: 6, lg: 8 }} spacing={{ base: 2, sm: 3 }}>
                    {propertyImages.map((image, index) => (
                      <Box
                        key={image._id}
                        position="relative"
                        cursor="pointer"
                        borderRadius="xl"
                        overflow="hidden"
                        border={currentImageIndex === index ? '3px solid' : '1px solid'}
                        borderColor={currentImageIndex === index ? 'brand.500' : borderColor}
                        onClick={() => setCurrentImageIndex(index)}
                        transition="all 0.3s cubic-bezier(0.4, 0, 0.2, 1)"
                        bg="white"
                        boxShadow="0 2px 8px rgba(0, 0, 0, 0.1)"
                        _hover={{
                          boxShadow: '0 8px 24px rgba(0, 0, 0, 0.2)',
                          transform: 'scale(1.08)'
                        }}
                      >
                        <Image
                          src={image.thumbnailUrl || image.originalUrl}
                          alt={`Thumbnail ${index + 1}`}
                          w="full"
                          h="80px"
                          objectFit="cover"
                          transition="all 0.3s ease"
                          _hover={{
                            filter: 'brightness(1.1) contrast(1.1)'
                          }}
                        />
                        {!isViewOnly && (
                          <IconButton
                            icon={<FaTrash />}
                            size="sm"
                            position="absolute"
                            top={2}
                            right={2}
                            colorScheme="red"
                            variant="solid"
                            onClick={(e) => {
                              e.stopPropagation();
                              handleDeleteImage(image);
                            }}
                            opacity={0}
                            transition="opacity 0.3s"
                            zIndex={10}
                            bg="red.500"
                            color="white"
                            borderRadius="full"
                            _hover={{
                              opacity: 1,
                              bg: "red.600",
                              transform: "scale(1.1)"
                            }}
                            boxShadow="0 4px 12px rgba(239, 68, 68, 0.4)"
                          />
                        )}
                        {/* Selection Indicator */}
                        {currentImageIndex === index && (
                          <Box
                            position="absolute"
                            top={0}
                            left={0}
                            right={0}
                            bottom={0}
                            bg="brand.500"
                            opacity="0.2"
                            pointerEvents="none"
                          />
                        )}
                      </Box>
                    ))}
                  </SimpleGrid>
                </Box>
              )}
            </VStack>
          </Box>
        </Box>
      </ModalContent>

      {/* Delete Confirmation Modal */}
      <DeleteConfirmationModal
        isOpen={isDeleteModalOpen}
        onClose={() => {
          setIsDeleteModalOpen(false);
          setImageToDelete(null);
        }}
        onConfirm={confirmDeleteImage}
        title="Delete Image"
        message={`Are you sure you want to delete this image? This action cannot be undone.`}
      />
    </Modal>
  );
};

export default PropertyPreview; 